spring:
  application: 
    name: store-mate-api
  
  config:
    import: optional:file:.env[.properties]
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
      
  jackson:
    time-zone: Asia/Bangkok
    
  flyway:
    locations: classpath:db/migration
    
  jpa:
    open-in-view: false
    
springdoc:
  packages-to-scan: com.sm.jeyz9.storemateapi.controllers
  
jwt-secret: ${JWT_SECRET}
jwt-expiration: 604800000
